### Create a new family
POST http://localhost:8080/families
Content-Type: application/json

{
  "familyName": "Whelan Family"
}

### Get all families
GET http://localhost:8080/families



### Get All Individuals
GET http://localhost:8080/individuals
Accept: application/json

### Add inividual
POST http://localhost:8080/individuals
Content-Type: application/json

{
  "name": "John Whelan",
  "dateOfBirth": "1990-03-15",
  "sex": "Male",
  "clinicalDiagnosis": "Condition X",
  "familyId": 1
}
